// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhnimurbheslfdzwvvfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5obmltdXJiaGVzbGZkend2dmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjk1OTQsImV4cCI6MjA2Njk0NTU5NH0.EPnvUw77TuQNwmXC-F4ZO1_nYdGh7UjtKi519Pur2Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});